<a href="https://colab.research.google.com/github/18121a05l8/basics-of-tensorflow/blob/main/Transforming_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf



In [5]:
vec = tf.constant([1., 2., 3., 4.])
mat = tf.reshape(vec, [2, 2])

print(mat)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [9]:
ten=tf.random.normal([2,3,4],2,1)
print(ten)
print(tf.slice(ten,[0,1,2],[2,2,2]))

tf.Tensor(
[[[2.9423957  4.7206674  3.2601018  2.7320113 ]
  [2.1281607  1.6669947  2.901515   1.6595201 ]
  [2.7076738  0.95358074 2.1499686  1.4508619 ]]

 [[1.9804631  2.9680622  1.5422122  1.0141459 ]
  [0.80276895 2.155648   1.0007138  1.9405538 ]
  [2.7656565  0.72714114 1.1914117  2.1926713 ]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[2.901515  1.6595201]
  [2.1499686 1.4508619]]

 [[1.0007138 1.9405538]
  [1.1914117 2.1926713]]], shape=(2, 2, 2), dtype=float32)


In [11]:
num=tf.random.normal([3,3],1,4)
print(num)

tf.Tensor(
[[-2.362496   -4.890255    2.9385462 ]
 [ 4.019184    3.0430489   4.332127  ]
 [ 5.849952   -0.26196933  4.8573236 ]], shape=(3, 3), dtype=float32)


In [12]:
print(tf.slice(num,[0,1],[3,2]))

tf.Tensor(
[[-4.890255    2.9385462 ]
 [ 3.0430489   4.332127  ]
 [-0.26196933  4.8573236 ]], shape=(3, 2), dtype=float32)


In [28]:
tensor1=tf.fill([3,3],0)
tensor2=tf.fill([3,3],1)
tensor3=tf.fill([3,3],2)
st=tf.stack([tensor1,tensor2,tensor3],axis=1)
print(st)


tf.Tensor(
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 0 0]
  [1 1 1]
  [2 2 2]]], shape=(3, 3, 3), dtype=int32)


In [27]:
print(tf.unstack(st,axis=1))

[<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>, <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>, <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)>]
